modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''

# --- Dependencies ------------------------------------------------------------
[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# We are an add-on for Iron's Spells 'n Spellbooks and must load after it.
[[dependencies.${mod_id}]]
modId = "${irons_spellbooks_id}"
type = "required"
versionRange = "${irons_spellbooks_version_range}"
ordering = "AFTER"
side = "BOTH"
